In [ ]:
import numpy as np
import pandas as pd
import plotly
import plotly.figure_factory as ff
import plotly.graph_objs as go
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import SGDClassifier
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

In [2]:
data = pd.read_csv('task_b.csv')
data=data.iloc[:,1:]

In [3]:
data.head()

f1            f2        f3    y
0  -195.871045 -14843.084171  5.532140  1.0
1 -1217.183964  -4068.124621  4.416082  1.0
2     9.138451   4413.412028  0.425317  0.0
3   363.824242  15474.760647  1.094119  0.0
4  -768.812047  -7963.932192  1.870536  0.0

In [4]:
data.corr()['y']

f1    0.067172
f2   -0.017944
f3    0.839060
y     1.000000
Name: y, dtype: float64

In [5]:
data.std()

f1      488.195035
f2    10403.417325
f3        2.926662
y         0.501255
dtype: float64

In [6]:
X=data[['f1','f2','f3']].values
Y=data['y'].values
print(X.shape)
print(Y.shape)

(200, 3)
(200,)


# What if our features are with different variance 

<pre>
* <b>As part of this task you will observe how linear models work in case of data having feautres with different variance</b>
* <b>from the output of the above cells you can observe that var(F2)>>var(F1)>>Var(F3)</b>

> <b>Task1</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' and check the feature importance

> <b>Task2</b>:
    1. Apply Logistic regression(SGDClassifier with logloss) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance
    2. Apply SVM(SGDClassifier with hinge) on 'data' after standardization 
       i.e standardization(data, column wise): (column-mean(column))/std(column) and check the feature importance

</pre>

In [9]:
clf = SGDClassifier(loss='log')
clf.fit(X,Y)
clf.coef_

array([[ 5219.97647851,  2400.73470378, 11208.9869683 ]])

In [11]:
clf = SGDClassifier(loss='hinge')
clf.fit(X,Y)
clf.coef_

array([[ 3396.97733029, 10605.57284778, 10786.26469191]])

<b> Observations </b>
<p> In Logistic Regression, features having the highest variance seems to have the lowest weights. Lower weights indicates minimal contribution towards computing the P(yq=+1). The magnitude of the weights directly corresponds to the feature importance </p>
<p> Variance= f2>f1>f3, Feature Importance: f3>f1>f2</p>
<p> High variance indicates larger spread of the data => which means the chance of many outliers to be present increases. So a higher variance feature might haver large contibution towards a outlier point. This increases the chance of the classifier to misclassify the outlier points </p>
<p> High variant features gets heavily penalized due to L2 regularization defined in the optimization objective and forces the corresponding weights of the high variant feature to be extremely low. Low variant features have less missclassifaction rate, which indicates a small penalty towards it weight contribution. So low variant features have higher weights </p>

<b>Observation(s) </b>
<p> In linear SVM, Feature Importance = f3=f2 > f1 </p>
<p> The points which are correctly classified have slack penalty =0, while incorrectly classified points have penalty proportional to the distance from the hyperplane </p>
<p> Even though features f2 and f3 have different variance, most of the points seems to have been lying in the correct direction of the hyperplane, therby having no penalty and maximum feature importance. </p>
<p> Feature f1 might have been in the opposite half space, and its corresponding weight vector according to hinge loss formulation incurs a heavy penalty, thus having the least feature importance </p>

# Task 2

In [16]:
#Column standardization
scaler = StandardScaler()
scaler.fit(data)
X=data[['f1','f2','f3']].values
Y=data['y'].values

In [17]:
clf = SGDClassifier(loss='log')
clf.fit(X,Y)
clf.coef_

array([[ 10083.48100934, -11135.73308097,  10741.43177964]])

In [18]:
clf = SGDClassifier(loss='hinge')
clf.fit(X,Y)
clf.coef_

array([[  3612.150116  , -12930.99880956,   9928.26147212]])

<b>Observations </b>
<p> For Logistic Regression once the data is standardized,the features become scale independant => all features have unit variance and 0 mean. In this case, all the points now reside in the unit hypercube dimensional space, thus equally contributing towards predicting the probablistic class labels. Thus all the features have almost equal feature importance </p>


<h3><font color='blue'> Make sure you write the observations for each task, why a particular feautre got more importance than others</font></h3>