<h1><font color='blue'> 8E and 8F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 8E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [131]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [132]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)

### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [133]:
# you can write your code here
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(X,y,test_size=0.2)
x_train,x_cv,y_train,y_cv = train_test_split(x_train,y_train,test_size=0.25)

In [134]:
clf = SVC(gamma=0.001,C=100.)
clf.fit(x_train,y_train)
clf.support_vectors_

array([[-0.07558036, -1.13041436, -0.38360149, -0.53539097,  0.23078377],
       [-0.52303789, -0.72788436, -0.27806923, -0.38366962,  0.24413493],
       [ 0.10331813,  1.5348955 ,  0.32840446,  0.48580068,  0.27848554],
       ...,
       [ 0.97310299,  0.3174213 ,  0.01838305,  0.03839771,  0.20991438],
       [ 1.25756657,  0.77995806, -0.04175077, -0.014569  ,  0.78309789],
       [-2.02548047,  0.29281338, -0.04573416, -0.04313701,  0.38643373]])

In [135]:
def rbf_kernel(x_i,query_point):
    diff=x_i-query_point
    return np.exp(-0.001*(diff**2))


In [136]:
def decision_function(xcv,dual,support_vectors_ ,intercept_ ):
    values=[]
    for x_q in xcv:
        decision_function=0
        for i in range(len(support_vectors_)):
            decision_function += dual[0][i] * np.exp(-0.001*np.linalg.norm(support_vectors_[i]-x_q)**2)
        values.append((decision_function+intercept_)[0])
    return values
values= decision_function(x_cv,clf.dual_coef_,clf.support_vectors_,clf.intercept_)

In [137]:
values[0:5]

[2.0583263917518044,
 -2.2651755619275074,
 0.31587655608619447,
 -2.7767940841212218,
 -2.8142110881247087]

In [138]:
fcv=clf.decision_function(x_cv)

array([ 2.05832639, -2.26517556,  0.31587656, -2.77679408, -2.81421109])

<h2><font color='Geen'> 8F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

# Task F

In [139]:
N_plus=np.sum(y_train)
N_minus = len(y_train)-N_plus
yplus=(N_plus+1)/(N_plus+2)
yminus=1/(N_minus+2)
ycv=[]
for value in y_cv:
    if value==1:
        ycv.append(yplus)
    else :
        ycv.append(yminus)

In [141]:
def log_loss(w,b,X,Y):
    N=len(X)
    sum_log=0
    for i in range(N):
        sum_log +=Y[i]*np.log10(sig(w,X[i],b)) + (1-Y[i])*np.log10(1-sig(w,X[i],b))
    return -1*sum_log/N
def sig(w,x,b):
    z=np.dot(w,x)+b
    return 1/(1+np.exp(-z))
def pred_prob(ftest,w,b):
    z= -np.dot(w,ftest)+b
    return 1/(1+np.exp(z))
def gradient_dw(x,y,w,b,alpha,N):
    dw=x*((y)-sigmoid(np.dot(w,x)+b))-((alpha*w)/N)
    return dw
def gradient_db(x,y,w,b):
    db = y-sigmoid(np.dot(w,x)+b)
    return db
def sigmoid(z):
    return 1/(1+np.exp(-z))


In [142]:
from sklearn.linear_model import SGDClassifier
from tqdm import tqdm
clf = SGDClassifier()
def train(X_train,y_train,epochs,alpha,eta0):
    train_loss=[]
    test_loss=[]

 #Here eta0 is learning rate
 #implement the code as follows
 # initalize the weights (call the initialize_weights(X_train[0]) function)
    w=np.zeros((1,))
    b=0
    for i in tqdm(range(epochs)):
        for j in range(len(X_train)):
            dw = gradient_dw(X_train[j],y_train[j],w,b,alpha,1)
            db = gradient_db(X_train[j],y_train[j],w,b)
            w = w + (eta0*dw)
            b = b + (eta0*db)
    
    return w,b

In [143]:
len(fcv)

1000

In [144]:
alpha=0.0001
eta0=0.0001
epochs=50
w,b = train(fcv,ycv,epochs,alpha,eta0)

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 17.73it/s]


In [145]:
w

array([1.223605])

In [156]:
clf.fit(x_train,y_train)


SGDClassifier()

In [157]:
ftest=clf.decision_function(x_test) #Values of decision function for all the points in X_test

In [158]:
prob=[] # Calculating P(Y=1/x) for all the points x in X_test 
for i in range(len(x_test)):
    prob.append(pred_prob(ftest[i],w,b))

In [160]:
prob[0:4]

[array([0.14199835]),
 array([8.24830642e-05]),
 array([0.94579661]),
 array([0.12699986])]

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm
